### PR TITLE
[Ready to merge]Jei Integration

### PR DESCRIPTION
**Pull request by sp-guip**
I implemented Jei integration to the machines:
pulverizer,powered furnace,Compactor,Refinery,Crucible,Sawmill,Smelter,Transposer.
this Pull request does need some additional work so please don't merge to master yet.

### CODE REVIEW

**Comment by sp-guip** [comment]
If you want any other machine integration type it here please.

**Comment by miuirussia** [comment]
/ThermalExpansion/build/sources/main/java/cofh/thermalexpansion/ThermalExpansion.java:175: error: cannot find symbol
		RefineryManager.loadRecipes();
		               ^
  symbol:   method loadRecipes()
  location: class RefineryManager

**Comment by miuirussia** [comment]
ThermalExpansion/build/sources/main/java/cofh/thermalexpansion/plugins/jei/JeiPlugin.java:112: error: method getRecipeList in class CompactorManager cannot be applied to given types;
        for (CompactorManager.RecipeCompactor recipe : CompactorManager.getRecipeList()) {
                                                                       ^
  required: Mode
  found: no arguments
  reason: actual and formal argument lists differ in length

**Comment by sp-guip** [comment]
works well in my environment.
that's not the way to report crash by the way...
if you want me to I can help you to set it up.

**Pull request closed without merging**
