### PR TITLE
Top Integration.

### PR DESCRIPTION
**Pull request by sp-guip**

### CODE REVIEW

**Comment by McJty** [comment]
While this PR will work it is more complicated then needed. You don't have to make abstraction of the TOP API like that. You can do it like in this tutorial:

http://modwiki.temporal-reality.com/mw/index.php/API_TOP-1.9

Check out the method addProbeInfo() in my block implementation. It can freely use interfaces from TOP even without having to distribute the API with the mod (which is bad). The requirement for needing those interfaces is only checked when that method is called and that method is only called when TOP is present

**Comment by sp-guip** [comment]
It's to to not repackage the api.

**Comment by McJty** [comment]
yes I know. But it is not needed. If you do it like I suggested then you also don't have to repackage the api. You can safely use interfaces from an API without that api having to be present at runtime as long as those methods are not called. Like I do it in my tutorial. There is no need for your complicated ProbeInfo wrapper

**Comment by sp-guip** [comment]
wouldn't the class still load and compile all imports event if TOP is not present?

**Comment by McJty** [comment]
Nope. I use this technique in all my mods (rftools etc) and it works. They don't have a hard dependency on TOP

**Comment by McJty** [comment]
Example:

https://github.com/McJty/RFTools/blob/1.11/src/main/java/mcjty/rftools/blocks/endergen/EndergenicBlock.java#L80-L89

**Comment by sp-guip** [comment]
but you're using mcjty.theoneprobe.api does it not proccess imports?(forge's runtime compiler)

**Comment by McJty** [comment]
imports themselves don't really do anything. It is only when you start using something that you import that it will load the class

**Comment by sp-guip** [comment]
Forge's compiler Is weird...
Sure I'll change it.

**Comment by McJty** [comment]
That's actually just java. Nothing to do with forge

**Comment by sp-guip** [comment]
From my experience it doesn't If you import a class It's loaded to memory for later use but I'll take your word for it.

**Comment by McJty** [comment]
Nope. Plenty of references for this. 'import' is just a shorthand so that the programmer doesn't have to type the full package+class. It otherwise has no effect:

http://stackoverflow.com/questions/7560721/when-does-the-jvm-load-classes
http://stackoverflow.com/questions/15378479/about-import-statement

**Comment by sp-guip** [comment]
cool

**Comment by sp-guip** [comment]
is that good mcjty?

**Comment by covers1624** [comment]
ClassLoading is a weird and complicated beast, does't really matter what TOP interfaces you implement or create new methods for Imo, as we have @Strippable with CoFHCore, but lemming may have a different stance on that. Basically, once McJty says this is all good to go it will be pulled. No pressure :P

**Comment by sp-guip** [comment]
fair enough

**Comment by McJty** [comment]
The changes seem to be ok. Normally I would expect that to work (doing it similarly in all my other mods)

**Pull request merged**
